### ISSUE TITLE
Authentication for multisite SSO

### ISSUE THREAD

**Issue by lmike-mnc** [markbarton/nodedomino#2]
Hi @markbarton 
**DomAuthSessId** is right only for single server authentication
In case SSO across several servers cookie must conteins **LtpaToken**

**Comment by markbarton** [comment]
Hi - good point - we haven't had the need for multi server authentication - I assume everything else stands?

This approach still stands us in good stead for dealing with Domino authentication, though I think the 10 / 11 release has better handling for authentication errors.

Will need to revisit / recreate the database as the original test cert / server has gone.

Looking at doing some lessons with the new DQL stuff and Vue, will be interesting to see how it compares to the REST API.

**Comment by lmike-mnc** [comment]
it's possible to apply small "patch" 
` //filter cookies to only DomAuthSessId

      const domino_auth_cookie = cookies.filter(function(cookie) {
      return cookie.name === "DomAuthSessId" || cookie.name === "LtpaToken";
      });`
